data:
  annotation : "../dataset/train.json"
  data_dir: "../dataset"

device: "cuda"
batch_size: 16

train:
  epoch: 5
  optimizer: "Adam"
  learning_rate: 0.001
  model: "Faster_R-CNN_ResNet50_FPN"
