DATA:
  annotation: "../dataset/test.json"
  data_dir: '../dataset/'

TEST:
  name: "coco_trash_test"
  config: "COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"
  ckp: "model_final.pth"
  output_dir: "./output"
  output_name: "faster_rcnn_R_101_FPN_3x_output.csv"